-- PaceLAB 용어 사전(glossary_terms).
-- 전 사용자 공유 reference 데이터. 이 마이그레이션 시드가 정본(source of truth)이며,
-- 웹 번들 fallback(src/entities/glossary/glossaryTerms.ts)은 같은 내용을 미러링한다.
-- 도메인 용어가 바뀌면 이 시드와 번들 fallback, 그리고 화면을 함께 갱신한다(완료 게이트 강제).

create table if not exists public.glossary_terms (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  term text not null,
  aka text[] not null default '{}',
  category text not null default 'basics',
  short_def text not null default '',
  detail text not null default '',
  related_slugs text[] not null default '{}',
  order_index integer not null default 100,
  approved boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists glossary_terms_category_order_idx
  on public.glossary_terms(category, order_index);

alter table public.glossary_terms enable row level security;

create policy "glossary_terms_select_approved"
  on public.glossary_terms for select
  to authenticated
  using (approved = true);

insert into public.glossary_terms (slug, term, aka, category, short_def, detail, related_slugs, order_index, approved)
values
  ('pace', '페이스', array['pace','분/km'], 'basics',
    '1km를 달리는 데 걸리는 시간(분:초/km).',
    '숫자가 작을수록 빠릅니다. 5:30/km는 1km를 5분 30초에 달린다는 뜻입니다.',
    array['cadence','hr-drift'], 10, true),
  ('cadence', '케이던스', array['cadence','spm'], 'basics',
    '1분당 걸음 수(spm).',
    '같은 페이스라도 케이던스가 높으면 보폭이 짧아 착지 충격과 부상 부담이 줄어드는 경향이 있습니다.',
    array['pace'], 20, true),
  ('rpe', 'RPE (체감 운동강도)', array['rpe','perceived exertion','체감강도'], 'basics',
    '스스로 느낀 힘듦 정도를 0~10으로 매긴 값.',
    '심박·페이스 숫자로 다 잡히지 않는 피로나 컨디션을 보완하는 주관 지표입니다. 코칭이 세션을 해석할 때 함께 봅니다.',
    array['hr-drift','recovery-cost'], 30, true),
  ('hr-drift', '심박 드리프트', array['drift','cardiac drift','드리프트'], 'basics',
    '같은 페이스인데도 후반에 심박이 올라가는 정도.',
    '전반 평균 심박과 후반 평균 심박의 차이로 봅니다. 더위·탈수·피로의 신호일 수 있습니다.',
    array['hr-zones','recovery-cost'], 40, true),

  ('hr-zones', '심박존 (Z0~Z5)', array['heart rate zone','zone','존','z2','z4'], 'heart_rate',
    '심박을 강도별로 나눈 구간.',
    '기본값은 Z1 회복 100~130, Z2 이지 131~145, Z3 146~155, Z4 템포 156~165, Z5 고강도 166bpm 이상입니다. 개인 역치심박이 입력되면 개인화한 존을 우선합니다.',
    array['lthr','tempo-ceiling'], 10, true),
  ('lthr', '역치심박 (LTHR)', array['lthr','lactate threshold','젖산역치','역치'], 'heart_rate',
    '젖산이 빠르게 쌓이기 시작하는 심박.',
    '30분 단독 전력주의 마지막 20분 평균 심박이 추정값입니다. PaceLAB 심박 상한 개인화의 1순위 기준이며, 직접 입력하면 가장 정확합니다.',
    array['max-hr','tempo-ceiling','hr-zones'], 20, true),
  ('max-hr', '최대심박 (HRmax)', array['max hr','hrmax','최대심박수'], 'heart_rate',
    '도달할 수 있는 가장 높은 심박.',
    '측정값을 입력하거나, 없으면 나이로 추정합니다. 실제 러닝에서 더 높은 심박이 찍히면 그 값으로 끌어올려 보정합니다.',
    array['tanaka','lthr'], 30, true),
  ('tanaka', 'Tanaka 공식', array['tanaka','208-0.7'], 'heart_rate',
    '나이로 최대심박을 추정하는 식 (208 − 0.7 × 나이).',
    '개인차가 ±10bpm 수준으로 크기 때문에 보수 신호로만 쓰고, 정확히 하려면 역치심박이나 측정 최대심박을 입력합니다.',
    array['max-hr','lthr'], 40, true),
  ('tempo-ceiling', '템포·이지·회복 상한', array['ceiling','상한','tempo cap','easy cap'], 'heart_rate',
    '세션 유형별로 넘지 않도록 권하는 심박 상한.',
    '고정 숫자(예: 165)가 아니라 개인 역치심박에서 파생합니다. 나이·심박·기록이 모두 없으면 상한을 만들지 않고 미설정으로 두고 페이스·RPE로 평가합니다.',
    array['lthr','hr-zones'], 50, true),

  ('easy', 'Easy (이지)', array['easy','이지런'], 'session_type',
    '대화가 가능한 편안한 저강도 러닝.',
    '페이스보다 심박 안정이 핵심입니다. 현재 기준은 최고/랩 심박 145bpm 이하 유지입니다.',
    array['recovery','easy-strides','hr-zones'], 10, true),
  ('recovery', 'Recovery (회복주)', array['recovery','회복런'], 'session_type',
    'Easy보다도 더 낮은 강도의 회복용 러닝.',
    '강훈련이나 롱런 다음날, 부하를 더하지 않고 회복 반응을 확인하는 세션입니다.',
    array['easy','recovery-cost'], 20, true),
  ('long-run', 'Long Run (롱런)', array['long run','롱런','장거리'], 'session_type',
    '낮은 강도로 오래 달려 지구력을 쌓는 세션.',
    '보통 주말에 배치하며, 강도보다 지속 시간/거리를 우선합니다.',
    array['lsd','steady-long'], 30, true),
  ('lsd', 'LSD', array['lsd','long slow distance'], 'session_type',
    'Long Slow Distance — 느리고 길게 달리는 저강도 롱런.',
    '평균/랩 심박이 Z1~Z2 중심이고 후반 드리프트가 작으면, 후반 페이스가 조금 올라가도 LSD로 봅니다.',
    array['long-run','steady-long'], 40, true),
  ('steady-long', 'Steady Long', array['steady long','스테디 롱런'], 'session_type',
    '의도적으로 일정 페이스를 유지하는 롱런.',
    'Z3 이상 비중, 후반 심박 상승, 의도적인 지속 페이스 상승이 함께 나타나면 LSD가 아니라 Steady Long으로 봅니다.',
    array['lsd','long-run'], 50, true),
  ('tempo', 'Tempo (템포)', array['tempo','템포런','threshold run'], 'session_type',
    '역치 부근 강도를 꾸준히 유지하는 세션.',
    '현재 기준은 최고 심박이 템포 상한을 넘지 않는 것입니다. 페이스 목표는 보조이며 후반 안정성을 먼저 봅니다.',
    array['tempo-ceiling','lthr'], 60, true),
  ('interval', '인터벌 (Interval)', array['interval','인터벌'], 'session_type',
    '고강도 구간과 회복 구간을 번갈아 반복하는 세션.',
    '심폐와 속도를 자극하는 품질 훈련으로, 회복·부상 게이트가 막히지 않을 때만 처방합니다.',
    array['race-tt','strides'], 70, true),
  ('strides', '스트라이드 (Strides)', array['strides','스트라이드','윈드스프린트'], 'session_type',
    '20초 안팎의 짧은 가속을 여러 번 반복하는 것.',
    '보통 Easy 러닝 끝에 붙여 러닝 폼과 순발력을 다듬습니다. 전력 질주가 아니라 가볍고 빠른 가속입니다.',
    array['easy-strides','easy'], 80, true),
  ('easy-strides', 'Easy + Strides', array['easy strides','이지 스트라이드'], 'session_type',
    'Easy 본주에 스트라이드를 더한 세션.',
    '현재 처방은 워밍업 10분 + 20초 가속/1분 40초 회복 × 8 + 쿨다운 15분입니다.',
    array['easy','strides'], 90, true),
  ('race-tt', 'Race / Time Trial', array['race','time trial','tt','레이스','타임트라이얼'], 'session_type',
    '대회 또는 전력으로 기록을 재는 시험주.',
    '수행능력 신호가 강한 세션이라 목표 가능성(Riegel 환산) 판단의 참고 기록으로 쓰입니다.',
    array['riegel','pb'], 100, true),
  ('strength', '보강운동', array['strength','근력운동','재활운동'], 'session_type',
    '부상 예방·재활을 돕는 참고용 근력 운동.',
    '통증 0~2/5 범위에서만 하고 다음날 악화되면 강도를 낮춥니다. 치료를 보장하지 않으며, 통증이 커지면 운동보다 중단·전문가 상담을 먼저 권합니다.',
    array['pain-level','injury-status'], 110, true),

  ('weekly-volume', '주간 거리', array['weekly volume','주간 볼륨','mileage'], 'load',
    '한 주 동안 누적한 러닝 거리.',
    '훈련량의 기본 척도입니다. 갑작스러운 증가는 회복 보수 신호로 봅니다.',
    array['load-spike','acute-load'], 10, true),
  ('acute-load', '급성 부하 (최근 7일)', array['acute load','최근 7일','atl'], 'load',
    '최근 7일에 쌓은 단기 훈련 부하.',
    '최근 7일과 직전 7일을 비교한 급격한 증가는 단정적 부상 예측이 아니라 보수적 경고로만 사용합니다.',
    array['chronic-load','load-spike'], 20, true),
  ('chronic-load', '만성 부하 (최근 30일)', array['chronic load','최근 30일','ctl'], 'load',
    '꾸준히 쌓아온 중장기 적응 부하.',
    '최근 30일과 직전 30일(31~60일)을 비교해 부하 추세를 봅니다. 단일 세션보다 반복 흐름을 우선합니다.',
    array['acute-load','load-spike'], 30, true),
  ('load-spike', '부하 급증 (spike / rising)', array['spike','rising','부하 급증'], 'load',
    '부하가 평소보다 가파르게 늘어난 상태.',
    '최근 30일이 직전 30일 대비 +50% 이상이면 spike, +30% 이상이면 rising으로 봅니다. 통증 신호와 겹칠 때만 강도를 강제로 낮춥니다.',
    array['overtraining','chronic-load'], 40, true),
  ('readiness', '목표 준비도', array['readiness','준비도'], 'load',
    '목표를 달성할 준비가 얼마나 됐는지 종합한 점수.',
    '수행능력 신호, 역치/템포 자극, 유산소 베이스, 롱런 기반, 일관성/회복 여유, 부상/회복 게이트를 가중평균해 보여줍니다. 단일 환산 기록만으로 판단하지 않습니다.',
    array['riegel','overtraining'], 50, true),
  ('overtraining', '과훈련 위험', array['overtraining','과훈련','overreaching'], 'load',
    '회복보다 부하가 앞서 누적된 위험 신호.',
    '부하 급증과 회복 부족, 통증·높은 RPE·낮은 컨디션이 겹칠 때 보수적으로 경고합니다.',
    array['load-spike','recovery-cost'], 60, true),

  ('trend-lens', '추세 Lens', array['trend lens','lens','렌즈'], 'trend',
    '누적 기록을 특정 질문 기준으로 다시 해석하는 분석 관점.',
    '“추세” 화면에서 목표 진전·유산소 효율·강도 분포·세션 품질·회복 비용 같은 Lens로 발전/퇴보와 다음 처방 영향을 봅니다.',
    array['goal-progress','aerobic-efficiency'], 10, true),
  ('goal-progress', '목표 진전', array['goal progress','목표 진척'], 'trend',
    '활성 목표에 얼마나 가까워지고 있는지 보는 Lens.',
    '최근 흐름과 수행능력 신호를 목표 기준으로 모아 발전 방향을 보여줍니다.',
    array['trend-lens','readiness'], 20, true),
  ('aerobic-efficiency', '유산소 효율', array['aerobic efficiency','유산소 효율'], 'trend',
    '같은 심박대에서 페이스가 좋아지고 있는지 보는 Lens.',
    '같은 심박대 샘플이 충분하고 기온·코스·고도 차이가 작을 때만 강한 개선 신호로 봅니다.',
    array['trend-lens','hr-drift'], 30, true),
  ('intensity-distribution', '강도 분포', array['intensity distribution','강도 분포','easy 비율'], 'trend',
    'Easy와 품질 훈련의 비중을 보는 Lens.',
    '지구력 훈련은 저강도 비중이 큰 분포를 기본 기준으로 삼습니다. Easy 여부는 세션 유형이 아니라 실제 심박·페이스로 계산합니다.',
    array['trend-lens','easy'], 40, true),
  ('session-quality', '세션 품질', array['session quality','세션 품질'], 'trend',
    '세션이 의도한 처방대로 수행됐는지 보는 Lens.',
    '예: 템포가 상한 안에서 안정적으로 유지됐는지, Easy가 충분히 쉬웠는지.',
    array['trend-lens','tempo'], 50, true),
  ('recovery-cost', '회복 비용', array['recovery cost','회복 비용'], 'trend',
    '세션 뒤 회복에 든 부담을 보는 Lens.',
    '긴 공백 단독은 휴식/기록 누락일 수 있어 약하게 봅니다. 통증·높은 RPE·낮은 컨디션 같은 반응 신호와 겹칠 때 회복 비용을 높입니다.',
    array['trend-lens','rpe','overtraining'], 60, true),

  ('pain-level', '통증 레벨 (0~5)', array['pain level','통증 점수','painLevel'], 'injury',
    '부위별 통증을 0~5로 매긴 값.',
    '0 없음, 1~2 관찰하며 보강 가능, 3 강훈련·롱런 상향 보류, 4~5 강도 하향·중단 검토가 필요한 강한 신호입니다.',
    array['severity','injury-checkin'], 10, true),
  ('severity', '심각도 (severity)', array['severity','심각도'], 'injury',
    '활성 부위 중 가장 높은 통증 레벨.',
    '여러 부위가 있으면 가장 강한 부위가 훈련 제한을 결정합니다. 의료 진단이 아니라 훈련 부하 조절용 위험 신호입니다.',
    array['pain-level','injury-status'], 20, true),
  ('injury-status', '부상 상태 (active / monitoring / resolved)', array['injury status','active','monitoring','resolved','완치'], 'injury',
    '부상 항목의 관리 단계.',
    'active 관리 중, monitoring 관찰 중, resolved 해소. resolved는 앱이 후보를 제안해도 사용자가 직접 확정합니다.',
    array['injury-checkin','severity'], 30, true),
  ('injury-area', '부상 부위', array['injury area','부위','normalizedAreas'], 'injury',
    '근육·힘줄·관절 단위로 정규화된 부위 선택값.',
    '햄스트링, 대퇴사두근, IT 밴드, 무릎, 정강이, 종아리, 아킬레스건, 발목, 족저근막, 고관절, 허리 등 신체 모델에서 선택합니다.',
    array['pain-level','injury-status'], 40, true),
  ('injury-checkin', '부상 체크인', array['injury check-in','체크인'], 'injury',
    '통증 변화와 완치 후보를 짧게 확인하는 절차.',
    '새 러닝이 들어온 뒤 active/monitoring 부상이 있으면 하루 1회 통증·악화 여부를 묻습니다. 결과는 사용자가 승인해야 상태에 반영됩니다.',
    array['injury-status','pain-level'], 50, true),

  ('active-goal', '활성 목표', array['active goal','활성 목표'], 'goal',
    '코칭의 1차 판단 기준이 되는 현재 목표.',
    '시작일, 목표일, 성공 기준, 전략을 함께 가집니다. 추천과 분석은 이 목표를 기준으로 합니다.',
    array['secondary-goal','target-date','success-criteria'], 10, true),
  ('secondary-goal', '보조 목표', array['secondary goal','보조 목표'], 'goal',
    '활성 목표를 바꾸지 않고 맥락으로만 참고하는 목표.',
    '예: “7:00/km로 Zone 2에서 편하게”처럼 장기·보조 목표는 활성 목표를 교체하지 않고 코칭 맥락으로 반영됩니다.',
    array['active-goal'], 20, true),
  ('success-criteria', '성공 기준', array['success criteria','성공 기준'], 'goal',
    '목표 달성 여부를 판정하는 기준.',
    '예: “10km 59:59 이내 완주”. 코칭은 성공 기준과 남은 기간을 보고 스케줄 유지/수정을 판단합니다.',
    array['active-goal','target-date'], 30, true),
  ('target-date', '목표일', array['target date','목표 날짜','d-day'], 'goal',
    '목표를 완성하려는 날짜.',
    '남은 기간에 맞춰 코칭이 주간 스케줄과 강도를 조정합니다.',
    array['active-goal','success-criteria'], 40, true),

  ('run-log', 'Run Log (러닝 기록)', array['run log','runlog','기록'], 'data',
    '한 번의 러닝 세션을 구조화해 저장한 단위.',
    '거리·시간·페이스·심박·케이던스·랩·경로 샘플·태그 등을 담습니다. “기록” 탭이 이 원장을 관리합니다.',
    array['healthkit','fit'], 10, true),
  ('healthkit', 'HealthKit', array['healthkit','건강 앱','apple health'], 'data',
    'Apple 건강 데이터 연동.',
    '로그인 상태에서 앱을 켜거나 다시 활성화하면 최신 기록 이후의 러닝만 자동으로 동기화합니다.',
    array['run-log','fit'], 20, true),
  ('fit', 'FIT import', array['fit','workoutdoors','.fit'], 'data',
    'Workoutdoors 등에서 내보낸 .fit 파일 가져오기.',
    '브라우저에서 로컬로 파싱해 러닝 기록 후보를 만듭니다. 원본 파일은 저장하지 않습니다.',
    array['run-log','healthkit'], 30, true),
  ('weather', '날씨 (Open-Meteo)', array['weather','open-meteo','날씨'], 'data',
    '무료 Open-Meteo API로 받는 날씨 요약.',
    '체감온도·강수확률·강수량 등을 러닝 준비 판단에 씁니다. 30도 이상이면 페이스보다 심박·체감강도를 우선합니다.',
    array['rpe'], 40, true),
  ('pb', 'PB (개인 최고기록)', array['pb','personal best','개인 기록'], 'data',
    '거리별 개인 최고기록.',
    '목표 가능성과 러너 레벨 판정, 당일 평가 문구에 반영됩니다.',
    array['riegel','race-tt'], 50, true),
  ('course-type', '코스 타입', array['course type','코스','flat','hilly','trail'], 'data',
    '러닝 코스의 지형 분류.',
    'Flat, Mixed, Hilly, Trail, Track, Treadmill로 나눕니다. 고도·거리로 추론한 제안값이며 사용자가 수정할 수 있습니다.',
    array['run-log'], 60, true),
  ('riegel', 'Riegel 예측', array['riegel','리겔','기록 환산'], 'data',
    '한 거리 기록으로 다른 거리 기록을 환산하는 공식.',
    '수행능력 신호가 있는 기록에 한해 목표 가능성의 참고 지표로만 씁니다. 확정 규칙이 아닙니다.',
    array['readiness','pb','race-tt'], 70, true)
on conflict (slug) do update
  set term = excluded.term,
      aka = excluded.aka,
      category = excluded.category,
      short_def = excluded.short_def,
      detail = excluded.detail,
      related_slugs = excluded.related_slugs,
      order_index = excluded.order_index,
      approved = excluded.approved,
      updated_at = now();
